version: '3.8'

services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - '80:3000'
    environment:
      NODE_ENV: development
    volumes:
      - /var/projects/frontend/.env:/app/.env
