version: '3.8'
services:
  app:
    build:
      context: .
    container_name: frontend-container
    image: nextjs-dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - /home/vira-dashboard-frontend/.env:/app/.env
