version: '3.8'

services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - /root/vira-panel/.env:/app/.env
